name = "JSONTypeProvider"
uuid = "b136afa1-cbce-4b41-a8e1-016fe2e389c3"
authors = ["mcmcgrath13 <m.c.mcgrath13@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
